<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Group', 'core');

/**
 * BaseGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property varchar $name
 * @property text $description
 * @property Doctrine_Collection $Users
 * @property Doctrine_Collection $Credentials
 * @property Doctrine_Collection $UserGroup
 * @property Doctrine_Collection $GroupCredential
 * 
 * @method integer             getId()              Returns the current record's "id" value
 * @method varchar             getName()            Returns the current record's "name" value
 * @method text                getDescription()     Returns the current record's "description" value
 * @method Doctrine_Collection getUsers()           Returns the current record's "Users" collection
 * @method Doctrine_Collection getCredentials()     Returns the current record's "Credentials" collection
 * @method Doctrine_Collection getUserGroup()       Returns the current record's "UserGroup" collection
 * @method Doctrine_Collection getGroupCredential() Returns the current record's "GroupCredential" collection
 * @method Group               setId()              Sets the current record's "id" value
 * @method Group               setName()            Sets the current record's "name" value
 * @method Group               setDescription()     Sets the current record's "description" value
 * @method Group               setUsers()           Sets the current record's "Users" collection
 * @method Group               setCredentials()     Sets the current record's "Credentials" collection
 * @method Group               setUserGroup()       Sets the current record's "UserGroup" collection
 * @method Group               setGroupCredential() Sets the current record's "GroupCredential" collection
 * 
 * @package    core
 * @subpackage model
 * @author     Brady Olsen
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGroup extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('groups');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'varchar', 128, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => 128,
             ));
        $this->hasColumn('description', 'text', null, array(
             'type' => 'text',
             ));

        $this->option('type', 'INNODB');
        $this->option('charset', 'utf8');
        $this->option('collate', 'utf8_unicode_ci');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('User as Users', array(
             'refClass' => 'UserGroup',
             'local' => 'group_id',
             'foreign' => 'user_id'));

        $this->hasMany('Credential as Credentials', array(
             'refClass' => 'GroupCredential',
             'local' => 'group_id',
             'foreign' => 'credential_id'));

        $this->hasMany('UserGroup', array(
             'local' => 'id',
             'foreign' => 'group_id'));

        $this->hasMany('GroupCredential', array(
             'local' => 'id',
             'foreign' => 'group_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}