<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('UserCredential', 'core');

/**
 * BaseUserCredential
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $credential_id
 * @property User $User
 * @property Credential $Credential
 * 
 * @method integer        getUserId()        Returns the current record's "user_id" value
 * @method integer        getCredentialId()  Returns the current record's "credential_id" value
 * @method User           getUser()          Returns the current record's "User" value
 * @method Credential     getCredential()    Returns the current record's "Credential" value
 * @method UserCredential setUserId()        Sets the current record's "user_id" value
 * @method UserCredential setCredentialId()  Sets the current record's "credential_id" value
 * @method UserCredential setUser()          Sets the current record's "User" value
 * @method UserCredential setCredential()    Sets the current record's "Credential" value
 * 
 * @package    core
 * @subpackage model
 * @author     Brady Olsen
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserCredential extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_credential');
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('credential_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));

        $this->option('type', 'INNODB');
        $this->option('charset', 'utf8');
        $this->option('collate', 'utf8_unicode_ci');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Credential', array(
             'local' => 'credential_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}