<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('UserGroup', 'core');

/**
 * BaseUserGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $group_id
 * @property User $User
 * @property Group $Group
 * 
 * @method integer   getUserId()   Returns the current record's "user_id" value
 * @method integer   getGroupId()  Returns the current record's "group_id" value
 * @method User      getUser()     Returns the current record's "User" value
 * @method Group     getGroup()    Returns the current record's "Group" value
 * @method UserGroup setUserId()   Sets the current record's "user_id" value
 * @method UserGroup setGroupId()  Sets the current record's "group_id" value
 * @method UserGroup setUser()     Sets the current record's "User" value
 * @method UserGroup setGroup()    Sets the current record's "Group" value
 * 
 * @package    core
 * @subpackage model
 * @author     Brady Olsen
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserGroup extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_group');
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('group_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));

        $this->option('type', 'INNODB');
        $this->option('charset', 'utf8');
        $this->option('collate', 'utf8_unicode_ci');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Group', array(
             'local' => 'group_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}