<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Credential', 'core');

/**
 * BaseCredential
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property varchar $name
 * @property varchar $description
 * @property Doctrine_Collection $Users
 * @property Doctrine_Collection $Groups
 * @property Doctrine_Collection $UserCredential
 * @property Doctrine_Collection $GroupCredential
 * 
 * @method integer             getId()              Returns the current record's "id" value
 * @method varchar             getName()            Returns the current record's "name" value
 * @method varchar             getDescription()     Returns the current record's "description" value
 * @method Doctrine_Collection getUsers()           Returns the current record's "Users" collection
 * @method Doctrine_Collection getGroups()          Returns the current record's "Groups" collection
 * @method Doctrine_Collection getUserCredential()  Returns the current record's "UserCredential" collection
 * @method Doctrine_Collection getGroupCredential() Returns the current record's "GroupCredential" collection
 * @method Credential          setId()              Sets the current record's "id" value
 * @method Credential          setName()            Sets the current record's "name" value
 * @method Credential          setDescription()     Sets the current record's "description" value
 * @method Credential          setUsers()           Sets the current record's "Users" collection
 * @method Credential          setGroups()          Sets the current record's "Groups" collection
 * @method Credential          setUserCredential()  Sets the current record's "UserCredential" collection
 * @method Credential          setGroupCredential() Sets the current record's "GroupCredential" collection
 * 
 * @package    core
 * @subpackage model
 * @author     Brady Olsen
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCredential extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('credential');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'varchar', 64, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => 64,
             ));
        $this->hasColumn('description', 'varchar', 255, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => 255,
             ));

        $this->option('type', 'INNODB');
        $this->option('charset', 'utf8');
        $this->option('collate', 'utf8_unicode_ci');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('User as Users', array(
             'refClass' => 'UserCredential',
             'local' => 'credential_id',
             'foreign' => 'user_id'));

        $this->hasMany('Group as Groups', array(
             'refClass' => 'GroupCredential',
             'local' => 'credential_id',
             'foreign' => 'group_id'));

        $this->hasMany('UserCredential', array(
             'local' => 'id',
             'foreign' => 'credential_id'));

        $this->hasMany('GroupCredential', array(
             'local' => 'id',
             'foreign' => 'credential_id'));
    }
}