all:
  core:
    class: sfDoctrineDatabase
    param:
      dsn: sqlite:///<?php echo dirname(__FILE__); ?>/../data/db/core.db

  ncbi_gene:
    class: sfDoctrineDatabase
    param:
      dsn: sqlite:///<?php echo dirname(__FILE__); ?>/../data/db/ncbi_gene.db


